### ISSUE TITLE
Adding API Tag in CSS

### ISSUE THREAD

**Issue by rum0s** [Paul-Reed/weather-icons#1]
Hello Paul,

I got a question concerning the API List. When using the current openweathermap node, I'm not receiving the "id" for the wi-own-{{id}}. Despite there is for example a weather:"clouds" entry.  As especially this one is missing in the API-List, I'm trying to add the the "clouds" tag in the weather-icons.css. However this does not work. Do you have any ideas how to fix this?

`.wi-wu-clouds:before ,
.wi-wu-cloudy:before {
  content: "\f013";
}`

Thank you very much and especially for your effort and bringing those nice icons to node-red 👍 
Stefan

**Comment by Paul-Reed** [comment]
Easiest way is to add edits to weather-icons.css and then change your NR link to load the non-minified css file instead of weather-icons.min.css
`<link rel="stylesheet" href="/weather-icons/mycss/weather-icons.css">`
So CSS entries would follow this format;
`.wi-wu-clouds:before {`
`  content: "\f013";`
`}`

**Comment by rum0s** [comment]
Many thanks for your reply! Things are working perfectly now. Sorry for my late answer.
